[controller]
output = xinput

[extra_buttons]
# Options: mouse4, mouse5, keyboard:F13, keyboard:a, etc.
# 'home' defaults to 'guide' (Xbox Home Button).
l4 = mouse4
r4 = mouse5
home = guide

[debug]
print_reports = false

